language: minimal

services:
  - docker

before_install:
  - docker pull smaug451/agda:basic

git:
  quiet: true

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - docker run --detach --name agda smaug451/agda:basic
  - docker exec agda bash -c "cd ~/; git clone https://github.com/Smaug123/agdaproofs.git; cd agdaproofs; git fetch; git checkout $BRANCH"
  - docker exec agda bash -c "cd ~/; agda Everything/Safe.agda && agda Everything/WithK.agda"
  - docker exec agda bash -c "find . -type f -name '*.agda' | sort > /tmp/agdas.txt; find . -type f -name '*.agdai' | sort | rev | cut -c 2- | rev > /tmp/compiled.txt; diff /tmp/agdas.txt /tmp/compiled.txt | grep '<' || true"
  - docker stop agda
