language: haskell

before_install:
  - cabal update
  - cabal install alex
  - cabal install happy
  - cabal install --only-dependencies Agda
  - travis wait cabal install Agda

git:
  quiet: true

script:
  agda Everything/Safe.agda && agda Everything/WithK.agda
